services:
  - type: worker
    name: crunchyroll-bot
    env: docker
    plan: starter_plus # This plan provides 1GB of RAM.
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false # Set the token in the Render dashboard
      - key: CRUNCHYROLL_COOKIES_FILE
        sync: false # Set the path to your cookies file in the Render dashboard
